### ISSUE TITLE
Is this tech still supported?

### ISSUE THREAD

**Issue by justinlevi** [videojs/videojs-vimeo#103]
With all the issues and PRs outstanding, just wondering if this tech is still being supported?

**Comment by gkatsev** [comment]
Yes. Unfortunately, it does end up being prioritized below other things that are going on, particularly, with the video.js 6.0 update that is happening soon. Any help is appreciated.
Though, we're probably going to start with merging in this PR https://github.com/videojs/videojs-vimeo/pull/95

**Comment by DiegoGallegos4** [comment]
Any news about merging that PR?

**Comment by ShinJii89** [comment]
When I want to play vimeo video I have error in console -> "Blocked „https://vimeo.com/api/v2/video/null.json?_=1494011215612&callback=jQuery21409546434388762466_1494011215611&format=json” because of incompatibility type MIME (X-Content-Type-Options: nosniff)." wtf?

VideoJS -> 5.19.2
This plugin -> newest

Youtube plugin works correctly...

**Comment by gkatsev** [comment]
It's merged and updated but no release just yet.
