### ISSUE TITLE
where do I download ../dist/Vimeo.min.js

### ISSUE THREAD

**Issue by designerwhocodes** [videojs/videojs-vimeo#88]

**Comment by designerwhocodes** [comment]
With the Vimeo.js file I'm getting this error also. Vimeo.js?ver=1.0.0:94Uncaught TypeError: Cannot read property 'getJSON' of undefined

**Comment by BrandonOCasey** [comment]
seems like this file is actually located in `lib/vimeo.min.js` rather than `dist`. Also the issue with getJSON seems to be the same issue as #74, which might be an issues with the version of jquery being used or something that has yet to be determined. If you have any other questions feel free to re-open this issue
