### ISSUE TITLE
Migration to Vimeo Player API — take two

### ISSUE THREAD

**Issue by jbourassa** [videojs/videojs-vimeo#92]
Hey,

I rewrote the Vimeo Tech using the Vimeo Player API. It's still not battle tested and somewhat of a work in progress, but I think I have the basic scenarios covered. Here it is: https://github.com/didacte/videojs-vimeo

Would you accept a PR that basically replaces the project with this source? Or would you recommend a way forward?

**Comment by jrglass** [comment]
@jbourassa, couldn't add an issue on the https://github.com/didacte/videojs-vimeo/issues page...

Thanks for whipping this new vimeo/video.js script up. I've gone ahead and implemented on our beta site as the old vimeo plugin never seemed to work. This one works great except for a few issues I've seen.

In the vimeo example, as compered with the youtube example (with youtube plugin for video.js) I'm seeing a real lag in time from when you press play to when it actually plays. Any ideas how to optimize so there is no lag?

Also, I have the google IMA plugin installed in order to play DFP ads before the videos. Works great with the youtube plugin. Is this possible with the new vimeo plugin as it currently isn't working.

Vimeo Example: http://beta.freeskier.com/videos/team-ride-park-city-goes-bang-2015-16-season-finale

Youtube Example: http://beta.freeskier.com/videos/david-wise-world-record-highest-air-on-a-hip-14-2-meters

Thanks!

**Comment by jbourassa** [comment]
Hey @jrglass 

> couldn't add an issue on the https://github.com/didacte/videojs-vimeo/issues page...
Any idea why? I can add issues and I see in the config page that they're enabled.

>I'm seeing a real lag in time from when you press play to when it actually plays.

Which browser are you using? It's decently fast for me, here's a gif if it happening real time:
![fast vimeo](https://cloud.githubusercontent.com/assets/224311/19252073/12f7f554-8f43-11e6-8ab6-e6914cb20761.gif)

You really are interacting with the real vimeo player at this point, we're not intercepting the click event or nothing. I don't think it has nothing to do with VideoJS. Do you feel it's slower than a normal Vimeo embed?


>Also, I have the google IMA plugin installed in order to play DFP ads before the videos. Works great with the youtube plugin. Is this possible with the new vimeo plugin as it currently isn't working.

I gave it a (very) quick look and couldn't figure how the IMA plugin works exactly, but the first blocker appears to be this: `VIDEOJS: Video.js: currentSrc method not defined for Vimeo playback technology. TypeError: this.tech_[a] is not a function`

I'd be happy to implement the `currentSrc` as it should, but there may be another issue down the road.

**Comment by jrglass** [comment]
> Which browser are you using? It's decently fast for me, here's a gif if it happening real time

On Google Chrome for Mac and still seeing a delay. On safari for mac I have to click the play button twice. It's definitely slower than a normal video embed.

>  I gave it a (very) quick look and couldn't figure how the IMA plugin works exactly, but the first blocker appears to be this: VIDEOJS: Video.js: currentSrc method not defined for Vimeo playback technology. TypeError: this.tech_[a] is not a function

The only reason I would use the vimeo plugin is to get Google DFP ads to play before it. Otherwise I would just use a normal vimeo embed. I know that the Google IMA plugin works in tandem with [videojs-contrib-ads](https://github.com/videojs/videojs-contrib-ads) plugin in order to work. Not sure if that helps at all but to get vimeo and youtube working along with DFP ads before it would be huge.

**Comment by gkatsev** [comment]
I think a rewrite is just fine. And it seems like you used our plugin generator which is great.
Unless someone from @videojs/core-committers has any objections, a PR for the re-write would be awesome.
We also try and give commit access to users who make meaningful contributions to a project and this would probably qualify.

**Comment by louim** [comment]
@jrglass @jbourassa The lag you are seeing on video start is definitely related to the ad(s) system(s). I tried playing the video on the example you posted with an ad blocker and the video starts immediately. Playing it without an ad blocker I get the 1-2 sec lag you mentioned.

My guess is that it tries to load ads before the video starts, and after erroring on `ERROR: TypeError: this.tech_[a] is not a function`, the normal playback of the video starts.

**Comment by jrglass** [comment]
@louim, that would make sense.

Have to look into how I can add the ads in with the vimeo videos sans error.
If anyone has any ideas let me know.

**Comment by jbourassa** [comment]
@jrglass I just pushed a few fixes, try it out, you may have success with Google IMA plugin

**Comment by jrglass** [comment]
@jbourassa, just the `dist/vimeojs-vimeo.js` file?

**Comment by jbourassa** [comment]
@jrglass Yes.

**Comment by jrglass** [comment]
@jbourassa, you, my friend, are a god.
Works like a charm: [http://beta.freeskier.com/videos/team-ride-park-city-goes-bang-2015-16-season-finale](http://beta.freeskier.com/videos/team-ride-park-city-goes-bang-2015-16-season-finale)

Where do I donate the beer?

**Comment by jbourassa** [comment]
Awh, just pass it along; help a fellow developer when you get the chance. Cheers!

**Comment by jrglass** [comment]
@jbourassa, finding that vimeo won't play on mobile/tablt. You can't click on the controls as if there's some transparent layer blocking the them. In "inspect" mode on chrome, I can sorta click a sliver of the very bottom of the play button. Can't get it to work at all on actual device. Very odd...

Also, I get a "no compatible source was found for this media" error every once and a while. Not sure why that happens when it just loaded fine. Could this be the order in which the scripts load?

Thanks again.

Example: http://freeskier.com/videos/must-watch-this-short-film-just-blew-our-freaking-minds-to-pieces

**Comment by jbourassa** [comment]
Mobile devices is (obviously) a priority for me as well so I'll look into it.

I experienced the other issue when trying your demo but couldn't reproduce it in a more vanilla scenario, so we'll see.

**Comment by jbourassa** [comment]
Actually, the standalone demo is working on iOS but not yours. I'm not sure what it is but it is not a priority for me to make it work w/ Google IMA. Let me know if you have more details or figure out what's not working.

Cheers,

**Comment by jrglass** [comment]
@jbourassa totally understandable. Going to roll back to a non-IMA setup for Vimeo plugin and test out to see what it produces. Keep you posted.

**Comment by jrglass** [comment]
@jbourassa, totally works fine when I remove Google IMA setup from the player. 

Example: http://beta.freeskier.com/videos/team-ride-park-city-goes-bang-2015-16-season-finale

Going to look a bit further into the issue as IMA must be applying some sort of layer to mobile version that is bigger than the actual player so you can't click the play button.

**Comment by jrglass** [comment]
@jbourassa, couldn't figure out the mobile issue. Haven't had much time. So I've gone ahead and just turned off ads on tablet/mobile and have them only running on desktop for now. Works great with this setup. But definitely losing a lot of potential impressions as majority of traffic is mobile.

Anyways, when I find some time, I'll look deeper. Let me know if you have any insights.

**Comment by gkatsev** [comment]
This has been merged.
